### PR TITLE
Support for rendering based on posted html data instead of a URL

### PR DESCRIPTION
**Pull request by sandord**
This PR adds a POST endpoint to the API that accepts a form post with an HTML string and a filename.

This can be very useful if you're looking for generating PDFs from HTML that's not hosted. This can be the case for security reasons but for convenience as well.

### CODE REVIEW

**Comment by zenato** [comment]
@sandord Thanks for your PR.
I respect your opinion. However, I think there are various solutions for converting HTML to PDF.
I hope headless-chrome will be used to render remote data more efficiently.

**Comment by sandord** [comment]
> I respect your opinion. However, I think there are various solutions for converting HTML to PDF.

That's okay, if you think this PR isn't the focus of puppeteer-renderer. I created it because I couldn't find a suitable library that's free and not using PhantomJS, which appears to be practically dead.

> I hope headless-chrome will be used to render remote data more efficiently.

I'm not sure what you mean?

**Comment by zenato** [comment]
It means that puppeteer-renderer wants to be used for remote data rendering such as crawling or brower testing.

**Comment by sandord** [comment]
> It means that puppeteer-renderer wants to be used for remote data rendering such as crawling or brower testing.

Ah, I see. Maybe that would be something to put at the top of the readme.

**Comment by zenato** [comment]
> Ah, I see. Maybe that would be something to put at the top of the readme.
I will consider this.

Would you mind if I close PR?

**Comment by sandord** [comment]
You can close the PR.

**Pull request closed without merging**
